/**
 * @kite-vpn/core — Default configuration templates
 *
 * Provides sensible default values for DNS, engine, merge strategy, and
 * routing rules.  These templates are used when no user configuration
 * exists yet, and as a base that user overrides are merged into.
 *
 * No `any` type is used anywhere in this file.
 */

import type {
  DnsConfig,
  EngineConfig,
  MergeStrategy,
  RoutingRule,
} from '@kite-vpn/types'

// ---------------------------------------------------------------------------
// DNS
// ---------------------------------------------------------------------------

/**
 * Default DNS configuration.
 *
 * Uses domestic DoH servers as primary nameservers and international
 * DoH servers as fallback.  The fallback filter triggers when a
 * response resolves to a non-CN GeoIP address, ensuring domestic
 * domains stay fast while foreign domains avoid DNS poisoning.
 */
export const DEFAULT_DNS_CONFIG: DnsConfig = {
  enabled: true,
  listen: '0.0.0.0:53',
  ipv6: false,
  enhancedMode: 'fake-ip',
  fakeIpRange: '198.18.0.1/16',
  nameservers: [
    'https://doh.pub/dns-query',
    'https://dns.alidns.com/dns-query',
  ],
  fallback: [
    'https://1.1.1.1/dns-query',
    'https://dns.google/dns-query',
    'https://dns.cloudflare.com/dns-query',
  ],
  fallbackFilter: {
    geoip: true,
    geoipCode: 'CN',
    ipcidr: ['240.0.0.0/4'],
  },
} as const

// ---------------------------------------------------------------------------
// Engine
// ---------------------------------------------------------------------------

/**
 * Default engine (mihomo core) configuration.
 *
 * Listens on the standard mixed port 7890 with the external controller
 * bound to localhost:9090.  LAN access is disabled by default for
 * security.  The proxy mode is `rule` (routing rules decide which
 * traffic is proxied).
 */
export const DEFAULT_ENGINE_CONFIG: EngineConfig = {
  mixedPort: 7890,
  allowLan: false,
  mode: 'rule',
  logLevel: 'info',
  externalController: '127.0.0.1:9090',
  dns: DEFAULT_DNS_CONFIG,
  profile: {
    storeSelected: true,
    storeFakeIp: false,
  },
} as const

// ---------------------------------------------------------------------------
// Merge strategy
// ---------------------------------------------------------------------------

/**
 * Default merge strategy used when combining multiple subscriptions.
 *
 * - Deduplicates by `server:port` so the same endpoint from different
 *   sources doesn't appear twice.
 * - Renames conflicting display names (appends source / numeric suffix).
 * - Groups output by geographic region with `url-test` sub-groups so
 *   the fastest node per region is selected automatically.
 * - No exclude / include patterns or rename rules are set by default.
 */
export const DEFAULT_MERGE_STRATEGY: MergeStrategy = {
  deduplication: 'by_server',
  nameConflict: 'rename',
  groupBy: 'region',
  regionGroupMode: 'url-test',
  excludePatterns: [],
  includePatterns: [],
  renameRules: [],
} as const

// ---------------------------------------------------------------------------
// Routing rules
// ---------------------------------------------------------------------------

/**
 * Name of the top-level proxy selector group referenced by routing rules.
 *
 * This MUST match the group name generated by the subscription merger
 * (see `merger.ts → TOP_GROUP_NAME`).
 */
const PROXY_GROUP = '🔰 节点选择'

/**
 * Default routing rules.
 *
 * The rule set follows a standard pattern for users in mainland China:
 *
 * 1. **Private / reserved IP ranges** → DIRECT (no-resolve to avoid leaks).
 * 2. **Common domestic domains** → DIRECT via GeoSite.
 * 3. **China IP ranges** → DIRECT via GeoIP.
 * 4. **Ad / tracking domains** → REJECT via GeoSite.
 * 5. **Catch-all MATCH** → Proxy group (everything else goes through proxy).
 *
 * Users can override or extend these rules per-profile.
 */
export const DEFAULT_RULES: readonly RoutingRule[] = [
  // ── Private / reserved networks ──────────────────────────────────────
  {
    type: 'IP-CIDR',
    payload: '127.0.0.0/8',
    target: 'DIRECT',
    noResolve: true,
  },
  {
    type: 'IP-CIDR',
    payload: '10.0.0.0/8',
    target: 'DIRECT',
    noResolve: true,
  },
  {
    type: 'IP-CIDR',
    payload: '172.16.0.0/12',
    target: 'DIRECT',
    noResolve: true,
  },
  {
    type: 'IP-CIDR',
    payload: '192.168.0.0/16',
    target: 'DIRECT',
    noResolve: true,
  },
  {
    type: 'IP-CIDR6',
    payload: '::1/128',
    target: 'DIRECT',
    noResolve: true,
  },
  {
    type: 'IP-CIDR6',
    payload: 'fc00::/7',
    target: 'DIRECT',
    noResolve: true,
  },
  {
    type: 'IP-CIDR6',
    payload: 'fe80::/10',
    target: 'DIRECT',
    noResolve: true,
  },

  // ── Link-local / special-use ─────────────────────────────────────────
  {
    type: 'IP-CIDR',
    payload: '100.64.0.0/10',
    target: 'DIRECT',
    noResolve: true,
  },
  {
    type: 'IP-CIDR',
    payload: '169.254.0.0/16',
    target: 'DIRECT',
    noResolve: true,
  },
  {
    type: 'IP-CIDR',
    payload: '224.0.0.0/4',
    target: 'DIRECT',
    noResolve: true,
  },
  {
    type: 'IP-CIDR',
    payload: '240.0.0.0/4',
    target: 'DIRECT',
    noResolve: true,
  },
  {
    type: 'IP-CIDR',
    payload: '255.255.255.255/32',
    target: 'DIRECT',
    noResolve: true,
  },

  // ── Domestic domains (GeoSite) ───────────────────────────────────────
  {
    type: 'GEOSITE',
    payload: 'cn',
    target: 'DIRECT',
  },

  // ── Domestic IPs (GeoIP) ─────────────────────────────────────────────
  {
    type: 'GEOIP',
    payload: 'CN',
    target: 'DIRECT',
  },

  // ── Ad / tracker blocking ────────────────────────────────────────────
  {
    type: 'GEOSITE',
    payload: 'category-ads-all',
    target: 'REJECT',
  },

  // ── Catch-all ────────────────────────────────────────────────────────
  {
    type: 'MATCH',
    payload: '',
    target: PROXY_GROUP,
  },
] as const
